#ifndef WORLD_SIM_GAME_PRESENTATION_PLAGUE_PROBABILITY_ARTIFACT_PROBE_H
#define WORLD_SIM_GAME_PRESENTATION_PLAGUE_PROBABILITY_ARTIFACT_PROBE_H

#include <stdio.h>

int game_presentation_plague_probability_artifact_probe(FILE *summary);

#endif
