@echo off
setlocal

gcc -O2 -Wall -Wextra -finput-charset=UTF-8 -fexec-charset=UTF-8 -I. -Isrc ^
  src\main.c ^
  src\game\game.c ^
  src\game\game_loop.c ^
  src\game\game_worldgen.c ^
  src\io\map_save.c ^
  src\io\map_save_regions.c ^
  src\core\event_log.c ^
  src\core\game_state.c ^
  src\core\country_focus.c ^
  src\core\dirty_flags.c ^
  src\core\profiler.c ^
  src\core\render_snapshot.c ^
  src\core\state_lock.c ^
  src\core\worldgen_progress.c ^
  src\data\country_names.c ^
  src\data\province_names.c ^
  src\data\game_tables.c ^
  src\world\world_gen.c ^
  src\world\world_seed.c ^
  src\world\mountain_gen.c ^
  src\world\terrain_query.c ^
  src\world\world_smoothing.c ^
  src\world\rivers.c ^
  src\sim\simulation.c ^
  src\sim\simulation_seed.c ^
  src\sim\simulation_month.c ^
  src\sim\simulation_scheduler.c ^
  src\sim\simulation_worker.c ^
  src\world\noise.c ^
  src\world\ports.c ^
  src\sim\ports.c ^
  src\sim\maritime.c ^
  src\sim\maritime_diag.c ^
  src\sim\sea_nav.c ^
  src\sim\route_potential.c ^
  src\sim\sea_lanes.c ^
  src\sim\territory_integrity.c ^
  src\sim\vassal.c ^
  src\sim\civilization_slots.c ^
  src\sim\civilization_uid.c ^
  src\sim\civ_colors.c ^
  src\sim\disorder.c ^
  src\sim\collapse.c ^
  src\sim\population.c ^
  src\sim\plague.c ^
  src\sim\civilization_metrics.c ^
  src\sim\decision_snapshot.c ^
  src\sim\technology.c ^
  src\sim\province.c ^
  src\sim\province_partition.c ^
  src\sim\region_boundary.c ^
  src\sim\regions_config.c ^
  src\sim\regions.c ^
  src\sim\regions_validate.c ^
  src\sim\regions_shape.c ^
  src\sim\regions_spawn.c ^
  src\sim\spawn.c ^
  src\sim\expansion.c ^
  src\sim\diplomacy.c ^
  src\sim\diplomacy_contact.c ^
  src\sim\diplomacy_names.c ^
  src\sim\war.c ^
  src\sim\war_front.c ^
  src\sim\war_resolution.c ^
  src\render\render.c ^
  src\render\render_context.c ^
  src\render\snapshot_ui.c ^
  src\render\render_common.c ^
  src\render\ui_format.c ^
  src\render\cartography_layers.c ^
  src\render\contour_paths.c ^
  src\render\vector_paths.c ^
  src\render\worldgen_progress_overlay.c ^
  src\render\diplomacy_map_anim.c ^
  src\render\map_render.c ^
  src\render\map_highlight.c ^
  src\render\terrain_present.c ^
  src\render\region_render.c ^
  src\render\map_labels.c ^
  src\render\route_render.c ^
  src\render\river_geometry.c ^
  src\render\river_render.c ^
  src\render\sea_lane_render.c ^
  src\render\plague_render.c ^
  src\render\plague_visual.c ^
  src\render\pause_menu_render.c ^
  src\render\panel_country.c ^
  src\render\panel_country_actions.c ^
  src\render\panel_country_cards.c ^
  src\render\panel_country_events.c ^
  src\render\panel_country_detail.c ^
  src\render\panel_country_tech.c ^
  src\render\panel_country_decision.c ^
  src\render\panel_country_population.c ^
  src\render\panel_country_resources.c ^
  src\render\panel_country_diplomacy.c ^
  src\render\panel_country_diplomacy_cards.c ^
  src\render\panel_country_disorder.c ^
  src\render\panel_country_diplomacy_hits.c ^
  src\render\panel_population_page.c ^
  src\render\panel_plague_page.c ^
  src\render\panel_worldgen.c ^
  src\render\panel_debug_worldgen.c ^
  src\render\panel_debug.c ^
  src\render\panel_population.c ^
  src\render\panel_info.c ^
  src\render\panel_map.c ^
  src\render\icons.c ^
  src\ui\ui_theme.c ^
  src\ui\ui_widgets.c ^
  src\ui\pause_menu.c ^
  src\ui\ui_actions.c ^
  src\ui\ui_worldgen_layout.c ^
  src\ui\ui_state.c ^
  src\ui\ui_layout.c ^
  src\ui\ui_sliders.c ^
  src\ui\ui_forms.c ^
  src\ui\ui_selection.c ^
  src\ui\ui_snapshot_read.c ^
  src\ui\ui.c ^
  -o world_sim.exe -lgdi32 -luser32 -lmsimg32 -lgdiplus -lcomdlg32 -mwindows
if errorlevel 1 exit /b %errorlevel%

endlocal
