@echo off
setlocal

if not exist build mkdir build
windres src\world_sim.rc -O coff -o build\world_sim_resource.o
if errorlevel 1 exit /b %errorlevel%

gcc -O2 -Wall -Wextra -finput-charset=UTF-8 -fexec-charset=UTF-8 -I. -Isrc ^
  src\main.c ^
  src\game\game.c ^
  src\game\game_loop.c ^
  src\game\game_player_actions.c ^
  src\game\game_vassal_actions.c ^
  src\game\game_worldgen.c ^
  src\game\game_worldgen_live_validation.c ^
  src\game\game_plague_baseline_probe.c ^
  src\game\game_plague_probe.c ^
  src\game\game_plague_probe_rules.c ^
  src\game\game_plague_probe_probability.c ^
  src\game\game_plague_probe_state.c ^
  src\game\game_plague_probe_spread.c ^
  src\game\game_plague_probe_population.c ^
  src\game\game_plague_probe_integration.c ^
  src\game\game_plague_performance_probe.c ^
  src\game\game_plague_probability_request.c ^
  src\game\game_expansion_perf_probe.c ^
  src\game\game_war_history_probe.c ^
  src\game\game_war_history_probe_fixture.c ^
  src\game\game_war_history_model_probe.c ^
  src\game\game_war_history_terminal_probe.c ^
  src\game\game_war_history_save_probe.c ^
  src\game\game_war_history_save_probe_fixture.c ^
  src\game\game_war_history_save_probe_codec.c ^
  src\game\game_war_history_save_probe_dynamic.c ^
  src\game\game_war_history_live_fixture.c ^
  src\game\game_decision_equivalence_probe.c ^
  src\game\game_decision_cache_probe.c ^
  src\game\game_decision_cache_probe_fixture.c ^
  src\game\game_decision_cache_probe_lifecycle.c ^
  src\game\game_decision_cache_probe_matrix.c ^
  src\game\game_pause_snapshot_coherence_probe.c ^
  src\game\game_pause_snapshot_coherence_probe_fixture.c ^
  src\game\game_pause_snapshot_coherence_probe_cases.c ^
  src\game\game_decision_stability_probe.c ^
  src\game\game_decision_topology_probe.c ^
  src\game\game_worldgen_probe.c ^
  src\game\game_worldgen_aridity_probe.c ^
  src\game\game_worldgen_aridity_calibration_metrics.c ^
  src\game\game_worldgen_aridity_calibration_options.c ^
  src\game\game_worldgen_aridity_calibration_matrix.c ^
  src\game\game_worldgen_aridity_calibration_artifacts.c ^
  src\game\game_worldgen_aridity_response_options.c ^
  src\game\game_worldgen_aridity_response_metrics.c ^
  src\game\game_worldgen_aridity_response_matrix.c ^
  src\game\game_worldgen_aridity_response_probe.c ^
  src\game\game_worldgen_aridity_response_projection_options.c ^
  src\game\game_worldgen_aridity_response_projection_histogram.c ^
  src\game\game_worldgen_aridity_response_projection_matrix.c ^
  src\game\game_worldgen_aridity_response_projection_probe.c ^
  src\game\game_worldgen_aridity_diminishing_oasis_histogram.c ^
  src\game\game_worldgen_aridity_diminishing_oasis_histogram_io.c ^
  src\game\game_worldgen_aridity_diminishing_options.c ^
  src\game\game_worldgen_aridity_diminishing_io.c ^
  src\game\game_worldgen_aridity_diminishing_matrix.c ^
  src\game\game_worldgen_aridity_diminishing_production.c ^
  src\game\game_worldgen_aridity_diminishing_production_matrix.c ^
  src\game\game_worldgen_aridity_diminishing_probe.c ^
  src\game\game_worldgen_coast_threshold_probe.c ^
  src\game\game_worldgen_coast_semantic_fixture.c ^
  src\game\game_worldgen_river_e2e_probe.c ^
 src\game\game_worldgen_failure_probe.c ^
 src\game\game_worldgen_failure_render_probe.c ^
 src\game\game_worldgen_snapshot_recovery_probe.c ^
  src\game\game_worldgen_live_validation_probe.c ^
  src\game\game_worldgen_commit_probe.c ^
  src\game\game_worldgen_diagnostics_probe.c ^
  src\game\game_worldgen_river_payload_probe.c ^
  src\game\game_worldgen_physical_probe.c ^
  src\game\game_worldgen_landform_semantics_probe.c ^
  src\game\game_worldgen_lake_lifecycle_probe.c ^
  src\game\game_worldgen_lake_lifecycle_render_probe.c ^
  src\game\game_worldgen_lake_qualification_probe.c ^
  src\game\game_worldgen_lake_semantics_probe.c ^
  src\game\game_worldgen_region_water_probe.c ^
  src\game\game_worldgen_hydrology_probe.c ^
  src\game\game_worldgen_hydrology_direction_probe.c ^
  src\game\game_worldgen_hydrology_invariant_probe.c ^
  src\game\game_worldgen_climate_probe.c ^
  src\game\game_worldgen_climate_calibration_worker.c ^
  src\game\game_worldgen_climate_calibration_metrics.c ^
  src\game\game_worldgen_climate_calibration_csv.c ^
  src\game\game_worldgen_climate_calibration_probe.c ^
  src\game\game_worldgen_mountain_shape_probe.c ^
  src\game\game_worldgen_terrain_probe.c ^
  src\game\game_crisis_probe.c ^
  src\game\game_alliance_lifecycle_probe.c ^
  src\game\game_alliance_record_probe.c ^
  src\game\game_military_alliance_probe.c ^
  src\game\game_military_alliance_rules_probe.c ^
  src\game\game_alliance_probe.c ^
  src\game\game_alliance_render_probe.c ^
  src\game\game_diplomacy_probe.c ^
  src\game\game_diplomacy_relation_probe.c ^
  src\game\game_diplomacy_tooltip_probe.c ^
  src\game\game_diplomacy_visual_probe.c ^
  src\game\game_presentation_probe.c ^
  src\game\game_presentation_probe_runner.c ^
  src\game\game_presentation_decision_artifact_fixture.c ^
  src\game\game_presentation_decision_artifact_probe.c ^
  src\game\game_presentation_visual_blocker_probe.c ^
  src\game\game_presentation_decision_stability_probe.c ^
  src\game\game_presentation_decision_stability_visual_contract_probe.c ^
  src\game\game_presentation_war_history_fixture.c ^
  src\game\game_presentation_war_history_probe.c ^
  src\game\game_presentation_war_history_visual_contract_probe.c ^
  src\game\game_presentation_plague_probe.c ^
  src\game\game_presentation_plague_probability_probe.c ^
  src\game\game_presentation_plague_probability_contract_probe.c ^
  src\game\game_presentation_plague_probability_artifact_probe.c ^
  src\game\game_presentation_plague_fixture.c ^
  src\game\game_presentation_plague_impact_probe.c ^
  src\game\game_presentation_plague_history_probe.c ^
  src\game\game_presentation_plague_interaction_probe.c ^
  src\game\game_presentation_plague_fog_probe.c ^
  src\game\game_presentation_worldgen_contract_probe.c ^
  src\game\game_presentation_worldgen_probe.c ^
  src\game\game_presentation_worldgen_controls_probe.c ^
  src\game\game_presentation_worldgen_controls_adapter_probe.c ^
  src\game\game_presentation_worldgen_controls_region_probe.c ^
  src\game\game_presentation_worldgen_controls_interaction_probe.c ^
  src\game\game_presentation_worldgen_initial_civs_probe.c ^
  src\game\game_presentation_worldgen_controls_artifact_probe.c ^
  src\game\game_presentation_worldgen_controls_artifact_render.c ^
  src\game\game_presentation_worldgen_controls_artifact_matrix.c ^
  src\game\game_presentation_worldgen_controls_artifact_assets.c ^
  src\game\game_presentation_worldgen_controls_resource_probe.c ^
  src\game\game_presentation_static_physical_probe.c ^
  src\game\game_presentation_static_camera_probe.c ^
  src\game\game_presentation_static_camera_resources.c ^
  src\game\game_presentation_static_physical_artifacts.c ^
  src\game\game_presentation_static_physical_metrics.c ^
  src\game\game_presentation_water_river_probe.c ^
  src\game\game_presentation_lake_semantics_probe.c ^
  src\game\game_presentation_river_style_probe.c ^
  src\game\game_presentation_coast_artifact_probe.c ^
  src\game\game_presentation_coast_multiscale_probe.c ^
  src\game\game_presentation_water_edge_probe.c ^
  src\game\game_presentation_coast_smoothing_probe.c ^
  src\game\game_presentation_coast_protection_probe.c ^
  src\game\game_presentation_coast_artifact_metrics.c ^
  src\game\game_presentation_coast_artifact_pattern.c ^
 src\game\game_presentation_water_surface_probe.c ^
 src\game\game_presentation_water_reference_probe.c ^
 src\game\game_presentation_water_legend_probe.c ^
  src\game\game_presentation_river_lod_probe.c ^
  src\game\game_presentation_river_terminal_probe.c ^
  src\game\game_presentation_ocean_surface_probe.c ^
  src\game\game_presentation_ocean_coherence_probe.c ^
  src\game\game_presentation_ocean_cache_probe.c ^
  src\game\game_presentation_map_probe.c ^
  src\game\game_presentation_diplomacy_probe.c ^
  src\game\game_presentation_diplomacy_sort_probe.c ^
  src\game\game_presentation_regression_probe.c ^
  src\game\game_presentation_interaction_probe.c ^
  src\game\game_presentation_layout_probe.c ^
  src\game\game_presentation_live_map_probe.c ^
  src\game\game_presentation_topbar_probe.c ^
  src\game\game_presentation_world_policy_probe.c ^
  src\game\game_presentation_world_announcement_event_probe.c ^
  src\game\game_presentation_world_announcement_layout_probe.c ^
  src\game\game_presentation_world_announcement_ui_probe.c ^
  src\game\game_economy_probe.c ^
  src\game\game_collapse_color_probe.c ^
  src\game\game_population_probe.c ^
  src\game\game_population_corner_probe.c ^
  src\io\map_save.c ^
  src\io\map_save_load_river_preflight.c ^
  src\io\map_save_river_paths.c ^
  src\io\map_save_civs.c ^
  src\io\map_save_regions.c ^
  src\io\map_save_state.c ^
  src\io\map_save_war_history.c ^
  src\io\map_save_validation.c ^
  src\io\map_save_world_physical.c ^
  src\io\map_save_plague.c ^
  src\core\event_log.c ^
  src\core\event_log_plague.c ^
  src\core\event_log_runtime.c ^
  src\core\event_log_classify.c ^
  src\core\world_announcement_store.c ^
  src\core\game_notifications.c ^
  src\core\event_log_history.c ^
  src\core\event_log_store.c ^
  src\core\city_display.c ^
  src\core\game_state.c ^
  src\core\country_focus.c ^
  src\core\dirty_flags.c ^
  src\core\load_progress.c ^
  src\core\plague_perf.c ^
  src\core\profiler.c ^
  src\core\render_snapshot.c ^
  src\core\render_snapshot_wind.c ^
  src\core\render_snapshot_river.c ^
  src\core\render_snapshot_river_lakes.c ^
  src\core\render_snapshot_cache.c ^
  src\core\render_snapshot_plague.c ^
  src\core\render_snapshot_plague_cache.c ^
  src\core\render_snapshot_plague_impact.c ^
  src\core\render_snapshot_civs.c ^
  src\core\render_snapshot_events.c ^
  src\core\render_snapshot_keys.c ^
  src\core\render_snapshot_war_history.c ^
  src\core\render_snapshot_profile.c ^
  src\core\render_snapshot_sections.c ^
  src\core\state_lock.c ^
  src\core\worldgen_progress.c ^
  src\core\worldgen_attempt.c ^
  src\core\worldgen_failure_notice.c ^
  src\core\worldgen_fault_injection.c ^
  src\data\country_names.c ^
  src\data\province_names.c ^
  src\data\game_tables.c ^
  src\data\plague_names.c ^
  src\world\world_gen.c ^
  src\world\world_gen_context.c ^
  src\world\world_gen_diagnostics.c ^
  src\world\world_gen_rng.c ^
  src\world\world_gen_elevation.c ^
  src\world\world_gen_land_mask.c ^
  src\world\world_gen_land_mask_metrics.c ^
  src\world\world_gen_land_mask_refine.c ^
  src\world\world_seed.c ^
  src\world\mountain_gen.c ^
  src\world\world_gen_climate.c ^
  src\world\world_gen_moisture.c ^
  src\world\world_gen_aridity_response.c ^
  src\world\world_gen_aridity_projection.c ^
  src\world\wind_vector.c ^
  src\world\world_gen_classify.c ^
  src\world\world_gen_classify_climate.c ^
  src\world\world_physical_state.c ^
  src\world\terrain_query.c ^
  src\world\world_smoothing.c ^
  src\world\rivers.c ^
  src\world\river_path_validation.c ^
  src\world\river_state.c ^
  src\world\river_drainage.c ^
  src\world\river_routing.c ^
  src\world\river_lakes.c ^
  src\world\river_lake_qualification.c ^
  src\world\river_lake_shape.c ^
  src\world\river_lake_final_validation.c ^
  src\world\river_flow.c ^
  src\world\river_mouths.c ^
  src\world\river_hydroclimate.c ^
  src\sim\civilization_names.c ^
  src\sim\simulation.c ^
  src\sim\simulation_seed.c ^
  src\sim\simulation_month.c ^
  src\sim\simulation_scheduler.c ^
  src\sim\simulation_worker.c ^
  src\sim\world_announcement.c ^
  src\sim\world_announcement_alliance.c ^
  src\sim\world_announcement_war.c ^
  src\sim\world_announcement_plague.c ^
  src\world\noise.c ^
  src\world\ports.c ^
  src\sim\ports.c ^
  src\sim\stability_decision.c ^
  src\sim\maritime.c ^
  src\sim\maritime_diag.c ^
  src\sim\sea_nav.c ^
  src\sim\route_potential.c ^
  src\sim\sea_lanes.c ^
  src\sim\territory_integrity.c ^
  src\sim\enclave_resolution.c ^
  src\sim\enclave_weights.c ^
  src\sim\fragmentation_diag.c ^
  src\sim\vassal.c ^
	  src\sim\civilization_slots.c ^
	  src\sim\civilization_uid.c ^
	  src\sim\civ_colors.c ^
	  src\sim\civ_color_repair.c ^
	  src\sim\disorder.c ^
  src\sim\economy.c ^
  src\sim\collapse.c ^
  src\sim\collapse_partition.c ^
  src\sim\collapse_single.c ^
  src\sim\population_aging.c ^
  src\sim\population_diagnostics.c ^
  src\sim\population_display_cohorts.c ^
  src\sim\population_military.c ^
  src\sim\population_mortality.c ^
  src\sim\population.c ^
  src\sim\plague.c ^
  src\sim\plague_engine.c ^
  src\sim\plague_episode.c ^
  src\sim\plague_rules.c ^
  src\sim\plague_probability.c ^
  src\sim\plague_state.c ^
  src\sim\plague_immunity.c ^
  src\sim\plague_metrics.c ^
  src\sim\plague_adjacency.c ^
  src\sim\plague_spread.c ^
  src\sim\plague_mortality.c ^
  src\sim\plague_disorder.c ^
  src\sim\plague_diagnostics.c ^
  src\sim\civilization_metrics.c ^
  src\sim\decision_snapshot.c ^
  src\sim\decision_snapshot_cache.c ^
  src\sim\expansion_land_topology.c ^
  src\sim\technology.c ^
  src\sim\province.c ^
  src\sim\province_partition.c ^
  src\sim\region_boundary.c ^
  src\sim\regions_config.c ^
  src\sim\regions_balance.c ^
  src\sim\regions.c ^
  src\sim\regions_land_anchor.c ^
  src\sim\regions_validate.c ^
  src\sim\regions_shape.c ^
  src\sim\regions_settlement.c ^
  src\sim\regions_port_policy.c ^
  src\sim\regions_spawn.c ^
src\sim\spawn.c ^
src\sim\expansion.c ^
src\sim\alliance_state.c ^
src\sim\alliance_query.c ^
src\sim\alliance_council.c ^
src\sim\alliance_records.c ^
src\sim\alliance_contact.c ^
src\sim\alliance_ai.c ^
src\sim\alliance_union.c ^
src\sim\alliance_power.c ^
src\sim\alliance_military.c ^
src\sim\alliance_names.c ^
src\sim\diplomacy.c ^
src\sim\diplomacy_year.c ^
  src\sim\diplomacy_policy.c ^
  src\sim\diplomacy_relation_score.c ^
  src\sim\diplomacy_stability.c ^
  src\sim\diplomacy_borders.c ^
  src\sim\diplomacy_contact.c ^
  src\sim\diplomacy_names.c ^
  src\sim\war_desire.c ^
  src\sim\war.c ^
  src\sim\war_history.c ^
  src\sim\war_terminal.c ^
  src\sim\war_transfer.c ^
  src\sim\war_economy.c ^
  src\sim\war_front.c ^
  src\sim\war_player_peace.c ^
  src\sim\war_query.c ^
  src\sim\war_resolution.c ^
  src\sim\war_names.c ^
  src\sim\war_state.c ^
  src\render\render.c ^
  src\render\render_partial_ui.c ^
  src\render\render_transient_ui.c ^
  src\render\render_layer_cache.c ^
  src\render\render_dynamic_overlay_cache.c ^
  src\render\render_allocation_diagnostics.c ^
  src\render\render_static_map_cache_border.c ^
  src\render\render_static_map_cache_fill.c ^
  src\render\render_static_map_cache.c ^
  src\render\render_static_map_cache_status.c ^
  src\render\render_static_map_surface.c ^
  src\render\render_static_scene.c ^
  src\render\render_static_scene_pool.c ^
  src\render\render_static_physical_cache.c ^
  src\render\coast_geometry.c ^
  src\render\render_static_physical_overlay_cache.c ^
  src\render\render_water_coverage.c ^
  src\render\render_water_coverage_raster.c ^
  src\render\render_water_coast_smoothing.c ^
  src\render\render_water_coast_presentation.c ^
  src\render\render_coast_pattern.c ^
  src\render\render_water_surface_cache.c ^
  src\render\render_world_physical_prewarm.c ^
  src\render\render_world_static_prewarm.c ^
  src\render\render_ocean_assets.c ^
  src\render\worldgen_ui_assets.c ^
  src\render\worldgen_ui_surface_cache.c ^
  src\render\panel_worldgen_controls.c ^
  src\render\render_ocean_decoration_rules.c ^
  src\render\render_ocean_decoration_cache.c ^
  src\render\render_ocean_decoration_items.c ^
  src\render\render_ocean_decoration_water.c ^
  src\render\render_ocean_coverage.c ^
  src\render\render_ocean_decoration.c ^
  src\render\render_ocean_texture.c ^
  src\render\render_ocean_static_mask.c ^
  src\render\render_ocean_motifs.c ^
  src\render\render_context.c ^
  src\render\snapshot_ui.c ^
  src\render\render_common.c ^
  src\render\country_identity_block.c ^
  src\render\map_display_policy.c ^
  src\render\map_shore_color_cache.c ^
  src\render\map_ownership_surface.c ^
  src\render\ui_format.c ^
  src\render\cartography_layers.c ^
  src\render\country_target_arrow.c ^
  src\render\contour_paths.c ^
  src\render\vector_paths.c ^
  src\render\load_progress_overlay.c ^
  src\render\panel_diplomacy_cache_key.c ^
  src\render\panel_view_model_cache.c ^
  src\render\panel_view_model_cache_keys.c ^
  src\render\worldgen_progress_overlay.c ^
  src\render\diplomacy_map_anim.c ^
  src\render\diplomacy_map_marker_cache.c ^
  src\render\map_render.c ^
  src\render\map_highlight.c ^
  src\render\map_highlight_batch.c ^
  src\render\map_highlight_contours.c ^
  src\render\map_highlight_edge_layer.c ^
  src\render\map_highlight_segments.c ^
  src\render\terrain_present.c ^
  src\render\region_render.c ^
  src\render\snapshot_map_layers.c ^
  src\render\wind_render.c ^
  src\render\map_labels.c ^
  src\render\map_label_alliance.c ^
  src\render\map_label_cache.c ^
  src\render\map_label_cache_key.c ^
  src\render\map_label_projection.c ^
  src\render\map_label_placement_pool.c ^
  src\render\map_label_style.c ^
  src\render\route_render.c ^
  src\render\river_geometry.c ^
  src\render\river_geometry_curve.c ^
  src\render\river_render.c ^
  src\render\river_topology.c ^
  src\render\river_lod_policy.c ^
  src\render\river_presentation_filter.c ^
  src\render\sea_lane_dash_cache.c ^
  src\render\sea_lane_render.c ^
  src\render\plague_render.c ^
  src\render\plague_visual.c ^
  src\render\profiling_switches.c ^
  src\render\pause_menu_render.c ^
  src\render\top_notifications.c ^
  src\render\panel_alliance_model.c ^
  src\render\panel_alliance_sections.c ^
  src\render\panel_alliance_vote_state.c ^
  src\render\panel_alliance_votes.c ^
  src\render\panel_alliance_history.c ^
  src\render\panel_alliance_council.c ^
  src\render\panel_alliance_detail.c ^
  src\render\panel_alliance.c ^
  src\render\panel_country.c ^
  src\render\panel_country_actions.c ^
  src\render\panel_country_cards.c ^
  src\render\panel_country_events.c ^
  src\render\panel_country_detail.c ^
  src\render\panel_country_tech.c ^
  src\render\panel_country_decision.c ^
  src\render\panel_country_decision_extra.c ^
  src\render\panel_country_population.c ^
  src\render\panel_country_population_cards.c ^
  src\render\panel_country_resources.c ^
  src\render\panel_country_diplomacy.c ^
  src\render\panel_country_diplomacy_cards.c ^
  src\render\panel_country_diplomacy_result.c ^
  src\render\panel_country_diplomacy_war_history.c ^
  src\render\panel_war_compare_bar.c ^
  src\render\panel_country_diplomacy_score.c ^
  src\render\panel_country_diplomacy_tooltip.c ^
  src\render\panel_country_disorder.c ^
  src\render\panel_country_diplomacy_hits.c ^
  src\render\panel_population_page.c ^
  src\render\panel_plague_page.c ^
  src\render\panel_plague_probability.c ^
  src\render\panel_plague_common.c ^
  src\render\panel_plague_live.c ^
  src\render\panel_plague_impact.c ^
  src\render\panel_plague_history.c ^
  src\render\panel_plague_chart.c ^
  src\render\panel_debug_plague.c ^
  src\render\panel_worldgen.c ^
  src\render\panel_worldgen_shell.c ^
  src\render\panel_worldgen_fingerprint.c ^
  src\render\panel_worldgen_physical.c ^
  src\render\panel_worldgen_climate.c ^
  src\render\panel_worldgen_hydrology.c ^
  src\render\panel_worldgen_legacy.c ^
  src\render\panel_debug_worldgen.c ^
  src\render\panel_debug_controls.c ^
  src\render\panel_debug_spikes.c ^
  src\render\panel_debug_perf.c ^
  src\render\panel_debug.c ^
  src\render\panel_population.c ^
  src\render\panel_info.c ^
  src\render\top_world_announcement.c ^
  src\render\top_world_announcement_plague.c ^
  src\render\top_world_announcement_resources.c ^
  src\render\top_world_announcement_surface.c ^
  src\render\panel_map_speed_badge.c ^
  src\render\panel_map_legend_glyphs.c ^
  src\render\panel_map_water_legend.c ^
  src\render\panel_map.c ^
  src\render\icons.c ^
  src\ui\ui_clay_theme.c ^
  src\ui\ui_clay_primitives.c ^
  src\ui\ui_clay_widgets.c ^
  src\ui\ui_theme.c ^
  src\ui\ui_widgets.c ^
  src\ui\color_picker.c ^
  src\ui\pause_menu.c ^
  src\ui\ui_actions.c ^
  src\ui\ui_alliance_panel_input.c ^
  src\ui\ui_country_target.c ^
  src\ui\ui_debug_input.c ^
  src\ui\ui_map_display.c ^
  src\ui\ui_invalidation.c ^
  src\ui\ui_notifications.c ^
  src\ui\ui_panel_hover.c ^
  src\ui\ui_world_announcement.c ^
  src\ui\world_announcement_queue.c ^
  src\ui\ui_pressed_state.c ^
  src\ui\ui_wheel.c ^
  src\ui\ui_worldgen_config_adapter.c ^
  src\ui\ui_worldgen_command.c ^
  src\ui\ui_worldgen_control_state.c ^
  src\ui\ui_worldgen_input.c ^
  src\ui\ui_worldgen_panel_layout.c ^
  src\ui\ui_worldgen_random.c ^
  src\ui\ui_worldgen_view.c ^
  src\ui\ui_worldgen_layout.c ^
  src\ui\ui_plague_fog.c ^
  src\ui\ui_plague_input.c ^
  src\ui\ui_plague_panel.c ^
  src\ui\ui_plague_panel_layout.c ^
  src\ui\ui_plague_probability.c ^
  src\ui\ui_state.c ^
  src\ui\ui_layout.c ^
  src\ui\ui_map_legend_layout.c ^
  src\ui\ui_map_input.c ^
  src\ui\ui_sliders.c ^
  src\ui\ui_shortcuts.c ^
  src\ui\ui_forms.c ^
  src\ui\ui_worldgen_legacy_forms.c ^
  src\ui\ui_selection.c ^
  src\ui\ui_snapshot_read.c ^
  src\ui\ui.c ^
  build\world_sim_resource.o ^
  -o world_sim.exe -lgdi32 -luser32 -lmsimg32 -lgdiplus -lcomdlg32 -mwindows
if errorlevel 1 exit /b %errorlevel%

endlocal
