@echo off
setlocal

if not exist build mkdir build
windres src\world_sim.rc -O coff -o build\world_sim_resource.o
if errorlevel 1 exit /b %errorlevel%

gcc -O2 -Wall -Wextra -finput-charset=UTF-8 -fexec-charset=UTF-8 -I. -Isrc ^
  src\main.c ^
  src\game\game.c ^
  src\game\game_loop.c ^
  src\game\game_player_actions.c ^
  src\game\game_vassal_actions.c ^
  src\game\game_worldgen.c ^
  src\game\game_expansion_perf_probe.c ^
  src\game\game_worldgen_probe.c ^
  src\game\game_crisis_probe.c ^
  src\game\game_alliance_lifecycle_probe.c ^
  src\game\game_alliance_record_probe.c ^
  src\game\game_military_alliance_probe.c ^
  src\game\game_military_alliance_rules_probe.c ^
  src\game\game_alliance_probe.c ^
  src\game\game_alliance_render_probe.c ^
  src\game\game_diplomacy_probe.c ^
  src\game\game_diplomacy_relation_probe.c ^
  src\game\game_diplomacy_tooltip_probe.c ^
  src\game\game_diplomacy_visual_probe.c ^
  src\game\game_presentation_probe.c ^
  src\game\game_presentation_map_probe.c ^
  src\game\game_economy_probe.c ^
  src\game\game_collapse_color_probe.c ^
  src\game\game_population_probe.c ^
  src\game\game_population_corner_probe.c ^
  src\io\map_save.c ^
  src\io\map_save_civs.c ^
  src\io\map_save_regions.c ^
  src\io\map_save_state.c ^
  src\core\event_log.c ^
  src\core\event_log_classify.c ^
  src\core\game_notifications.c ^
  src\core\event_log_history.c ^
  src\core\event_log_store.c ^
  src\core\city_display.c ^
  src\core\game_state.c ^
  src\core\country_focus.c ^
  src\core\dirty_flags.c ^
  src\core\load_progress.c ^
  src\core\plague_perf.c ^
  src\core\profiler.c ^
  src\core\render_snapshot.c ^
  src\core\render_snapshot_cache.c ^
  src\core\render_snapshot_civs.c ^
  src\core\render_snapshot_events.c ^
  src\core\render_snapshot_keys.c ^
  src\core\render_snapshot_profile.c ^
  src\core\render_snapshot_sections.c ^
  src\core\state_lock.c ^
  src\core\worldgen_progress.c ^
  src\data\country_names.c ^
  src\data\province_names.c ^
  src\data\game_tables.c ^
  src\world\world_gen.c ^
  src\world\world_seed.c ^
  src\world\mountain_gen.c ^
  src\world\terrain_query.c ^
  src\world\world_smoothing.c ^
  src\world\rivers.c ^
  src\sim\civilization_names.c ^
  src\sim\simulation.c ^
  src\sim\simulation_seed.c ^
  src\sim\simulation_month.c ^
  src\sim\simulation_scheduler.c ^
  src\sim\simulation_worker.c ^
  src\world\noise.c ^
  src\world\ports.c ^
  src\sim\ports.c ^
  src\sim\stability_decision.c ^
  src\sim\maritime.c ^
  src\sim\maritime_diag.c ^
  src\sim\sea_nav.c ^
  src\sim\route_potential.c ^
  src\sim\sea_lanes.c ^
  src\sim\territory_integrity.c ^
  src\sim\enclave_resolution.c ^
  src\sim\enclave_weights.c ^
  src\sim\fragmentation_diag.c ^
  src\sim\vassal.c ^
	  src\sim\civilization_slots.c ^
	  src\sim\civilization_uid.c ^
	  src\sim\civ_colors.c ^
	  src\sim\civ_color_repair.c ^
	  src\sim\disorder.c ^
  src\sim\economy.c ^
  src\sim\collapse.c ^
  src\sim\collapse_partition.c ^
  src\sim\collapse_single.c ^
  src\sim\population_aging.c ^
  src\sim\population_diagnostics.c ^
  src\sim\population_display_cohorts.c ^
  src\sim\population_military.c ^
  src\sim\population_mortality.c ^
  src\sim\population.c ^
  src\sim\plague.c ^
  src\sim\civilization_metrics.c ^
  src\sim\decision_snapshot.c ^
  src\sim\technology.c ^
  src\sim\province.c ^
  src\sim\province_partition.c ^
  src\sim\region_boundary.c ^
  src\sim\regions_config.c ^
  src\sim\regions_balance.c ^
  src\sim\regions.c ^
  src\sim\regions_validate.c ^
  src\sim\regions_shape.c ^
  src\sim\regions_settlement.c ^
  src\sim\regions_port_policy.c ^
  src\sim\regions_spawn.c ^
src\sim\spawn.c ^
src\sim\expansion.c ^
src\sim\alliance_state.c ^
src\sim\alliance_query.c ^
src\sim\alliance_council.c ^
src\sim\alliance_records.c ^
src\sim\alliance_contact.c ^
src\sim\alliance_ai.c ^
src\sim\alliance_union.c ^
src\sim\alliance_power.c ^
src\sim\alliance_military.c ^
src\sim\alliance_names.c ^
src\sim\diplomacy.c ^
src\sim\diplomacy_year.c ^
  src\sim\diplomacy_policy.c ^
  src\sim\diplomacy_relation_score.c ^
  src\sim\diplomacy_stability.c ^
  src\sim\diplomacy_borders.c ^
  src\sim\diplomacy_contact.c ^
  src\sim\diplomacy_names.c ^
  src\sim\war_desire.c ^
  src\sim\war.c ^
  src\sim\war_transfer.c ^
  src\sim\war_economy.c ^
  src\sim\war_front.c ^
  src\sim\war_player_peace.c ^
  src\sim\war_query.c ^
  src\sim\war_resolution.c ^
  src\sim\war_names.c ^
  src\sim\war_state.c ^
  src\render\render.c ^
  src\render\render_layer_cache.c ^
  src\render\render_static_map_cache_border.c ^
  src\render\render_static_map_cache_fill.c ^
  src\render\render_static_map_cache.c ^
  src\render\render_static_map_cache_status.c ^
  src\render\render_static_scene.c ^
  src\render\render_ocean_assets.c ^
  src\render\render_ocean_decoration_rules.c ^
  src\render\render_ocean_decoration_water.c ^
  src\render\render_ocean_decoration.c ^
  src\render\render_ocean_motifs.c ^
  src\render\render_context.c ^
  src\render\snapshot_ui.c ^
  src\render\render_common.c ^
  src\render\map_display_policy.c ^
  src\render\map_ownership_surface.c ^
  src\render\ui_format.c ^
  src\render\cartography_layers.c ^
  src\render\country_target_arrow.c ^
  src\render\contour_paths.c ^
  src\render\vector_paths.c ^
  src\render\load_progress_overlay.c ^
  src\render\panel_diplomacy_cache_key.c ^
  src\render\panel_view_model_cache.c ^
  src\render\worldgen_progress_overlay.c ^
  src\render\diplomacy_map_anim.c ^
  src\render\map_render.c ^
  src\render\map_highlight.c ^
  src\render\map_highlight_batch.c ^
  src\render\map_highlight_contours.c ^
  src\render\map_highlight_edge_layer.c ^
  src\render\map_highlight_segments.c ^
  src\render\terrain_present.c ^
  src\render\region_render.c ^
  src\render\snapshot_map_layers.c ^
  src\render\map_labels.c ^
  src\render\map_label_alliance.c ^
  src\render\map_label_cache.c ^
  src\render\map_label_style.c ^
  src\render\route_render.c ^
  src\render\river_geometry.c ^
  src\render\river_render.c ^
  src\render\sea_lane_dash_cache.c ^
  src\render\sea_lane_render.c ^
  src\render\plague_render.c ^
  src\render\plague_visual.c ^
  src\render\profiling_switches.c ^
  src\render\pause_menu_render.c ^
  src\render\top_notifications.c ^
  src\render\panel_alliance_model.c ^
  src\render\panel_alliance_sections.c ^
  src\render\panel_alliance_vote_state.c ^
  src\render\panel_alliance_votes.c ^
  src\render\panel_alliance_history.c ^
  src\render\panel_alliance_council.c ^
  src\render\panel_alliance_detail.c ^
  src\render\panel_alliance.c ^
  src\render\panel_country.c ^
  src\render\panel_country_actions.c ^
  src\render\panel_country_cards.c ^
  src\render\panel_country_events.c ^
  src\render\panel_country_detail.c ^
  src\render\panel_country_tech.c ^
  src\render\panel_country_decision.c ^
  src\render\panel_country_decision_extra.c ^
  src\render\panel_country_population.c ^
  src\render\panel_country_population_cards.c ^
  src\render\panel_country_resources.c ^
  src\render\panel_country_diplomacy.c ^
  src\render\panel_country_diplomacy_cards.c ^
  src\render\panel_country_diplomacy_score.c ^
  src\render\panel_country_diplomacy_tooltip.c ^
  src\render\panel_country_disorder.c ^
  src\render\panel_country_diplomacy_hits.c ^
  src\render\panel_population_page.c ^
  src\render\panel_plague_page.c ^
  src\render\panel_worldgen.c ^
  src\render\panel_debug_worldgen.c ^
  src\render\panel_debug_controls.c ^
  src\render\panel_debug_spikes.c ^
  src\render\panel_debug_perf.c ^
  src\render\panel_debug.c ^
  src\render\panel_population.c ^
  src\render\panel_info.c ^
  src\render\panel_map_speed_badge.c ^
  src\render\panel_map.c ^
  src\render\icons.c ^
  src\ui\ui_clay_theme.c ^
  src\ui\ui_clay_primitives.c ^
  src\ui\ui_clay_widgets.c ^
  src\ui\ui_theme.c ^
  src\ui\ui_widgets.c ^
  src\ui\color_picker.c ^
  src\ui\pause_menu.c ^
  src\ui\ui_actions.c ^
  src\ui\ui_alliance_panel_input.c ^
  src\ui\ui_country_target.c ^
  src\ui\ui_debug_input.c ^
  src\ui\ui_map_display.c ^
  src\ui\ui_invalidation.c ^
  src\ui\ui_notifications.c ^
  src\ui\ui_pressed_state.c ^
  src\ui\ui_wheel.c ^
  src\ui\ui_worldgen_layout.c ^
  src\ui\ui_state.c ^
  src\ui\ui_layout.c ^
  src\ui\ui_map_input.c ^
  src\ui\ui_sliders.c ^
  src\ui\ui_forms.c ^
  src\ui\ui_selection.c ^
  src\ui\ui_snapshot_read.c ^
  src\ui\ui.c ^
  build\world_sim_resource.o ^
  -o world_sim.exe -lgdi32 -luser32 -lmsimg32 -lgdiplus -lcomdlg32 -mwindows
if errorlevel 1 exit /b %errorlevel%

endlocal
