#ifndef WORLD_SIM_RENDER_ICONS_H
#define WORLD_SIM_RENDER_ICONS_H

#include "core/game_types.h"

typedef enum {
    ICON_BATTLE,
    ICON_EXPANSION,
    ICON_POPULATION,
    ICON_COUNTRY_DEFENSE,
    ICON_CULTURE,
    ICON_WATER,
    ICON_GEOGRAPHY,
    ICON_CLIMATE,
    ICON_HABITABILITY,
    ICON_TILE_DEFENSE,
    ICON_ATTACK,
    ICON_FOOD,
    ICON_LIVESTOCK,
    ICON_WOOD,
    ICON_ORE,
    ICON_STONE,
    ICON_CITY_CAPITAL,
    ICON_DISORDER,
    ICON_TERRITORY,
    ICON_MIGRATION,
    ICON_ECONOMY,
    ICON_PRODUCTION,
    ICON_INNOVATION,
    ICON_GOVERNANCE,
    ICON_COHESION,
    ICON_LOGISTICS,
    ICON_ADAPTATION,
    ICON_MONEY,
    ICON_MILITARY,
    ICON_COMMERCE,
    ICON_CITY_OUTPOST,
    ICON_CITY_VILLAGE,
    ICON_CITY_TOWN,
    ICON_CITY_STAGE,
    ICON_HARBOR,
    ICON_COUNT
} IconId;

void draw_icon(HDC hdc, IconId icon, RECT rect, COLORREF fallback);

#endif
