#ifndef WORLD_SIM_PROFILING_SWITCHES_H
#define WORLD_SIM_PROFILING_SWITCHES_H

enum {
    PROFILING_SWITCH_SIDE_PANEL_DETAIL,
    PROFILING_SWITCH_HIGHLIGHT,
    PROFILING_SWITCH_CITY_OVERLAY,
    PROFILING_SWITCH_MAP_LABELS,
    PROFILING_SWITCH_STATIC_SCENE,
    PROFILING_SWITCH_DIPLOMACY_ANIMATION,
    PROFILING_SWITCH_MAP_LEGEND,
    PROFILING_SWITCH_PANEL_CACHE_REBUILD,
    PROFILING_SWITCH_COUNT
};

int profiling_switch_enabled(int switch_id);
void profiling_switch_toggle(int switch_id);

#endif
