#ifndef WORLD_SIM_CONSTANTS_H
#define WORLD_SIM_CONSTANTS_H

#define MAP_W 800
#define MAP_H 600
#define MAX_CIVS 16
#define MAX_CITIES 128
#define NAME_LEN 64
#define WINDOW_W 1920
#define WINDOW_H 1080
#define TOP_BAR_H 62
#define DEFAULT_SIDE_PANEL_W 520
#define MIN_SIDE_PANEL_W 500
#define MAX_SIDE_PANEL_W 720
#define BOTTOM_BAR_H 44
#define TIMER_ID 1
#define FORM_X_PAD 18
#define CITY_MIN_DISTANCE 18
#define MAX_POPULATION 2000000000
#define MAX_RIVER_PATHS 96
#define MAX_RIVER_POINTS 280
#define MAX_MARITIME_ROUTES 160
#define MAX_MARITIME_ROUTE_POINTS 96
#define POP_COHORT_COUNT 8

#endif
