#ifndef WORLD_SIM_EVENT_LOG_TYPES_H
#define WORLD_SIM_EVENT_LOG_TYPES_H

typedef enum {
    EVENT_TYPE_GENERIC,
    EVENT_TYPE_EXPANSION_CLAIMED,
    EVENT_TYPE_WAR_STARTED,
    EVENT_TYPE_WAR_FRONT_SEVERED,
    EVENT_TYPE_BATTLE_RESOLVED,
    EVENT_TYPE_TRUCE_SIGNED,
    EVENT_TYPE_COLLAPSE_SUCCEEDED,
    EVENT_TYPE_COLLAPSE_FAILED,
    EVENT_TYPE_PLAGUE_STARTED,
    EVENT_TYPE_PLAGUE_SPREAD,
    EVENT_TYPE_PLAGUE_ENDED,
    EVENT_TYPE_VASSAL_CREATED,
    EVENT_TYPE_VASSAL_RELEASED,
    EVENT_TYPE_VASSAL_TRANSFERRED,
    EVENT_TYPE_VASSAL_PEACEFUL_INDEPENDENCE,
    EVENT_TYPE_VASSAL_INDEPENDENCE_WAR,
    EVENT_TYPE_VASSAL_COLLAPSE_INDEPENDENCE,
    EVENT_TYPE_VASSAL_SELF_COLLAPSE_RELEASED,
    EVENT_TYPE_VASSAL_ANNEXED,
    EVENT_TYPE_PERFORMANCE_THROTTLED,
    EVENT_TYPE_PERFORMANCE_SLOW_CALL,
    EVENT_TYPE_SCHEDULER_YIELD,
    EVENT_TYPE_WORLD_GENERATION_NOTICE,
    EVENT_TYPE_DISORDER_CHANGED,
    EVENT_TYPE_DEBUG_NOTICE,
    EVENT_TYPE_DEEP_SEA_ROUTE_CREATED,
    EVENT_TYPE_DEEP_SEA_ROUTE_FAILED,
    EVENT_TYPE_CIVIL_UNREST_TRIGGERED,
    EVENT_TYPE_ENCLAVE_JOINED,
    EVENT_TYPE_ENCLAVE_INDEPENDENT,
    EVENT_TYPE_ENCLAVE_FAILED,
    EVENT_TYPE_CIV_CREATED,
    EVENT_TYPE_DIPLOMACY_PEACE,
    EVENT_TYPE_DIPLOMACY_TENSE,
    EVENT_TYPE_TREASURY_INDEMNITY,
    EVENT_TYPE_STABILITY_PROJECT,
    EVENT_TYPE_MERCENARIES_HIRED,
    EVENT_TYPE_DIPLOMACY_ALLIANCE,
    EVENT_TYPE_DIPLOMACY_ALLIANCE_ENDED,
    EVENT_TYPE_WAR_FORCED_ALLIANCE_EXIT,
    EVENT_TYPE_DIPLOMACY_ALLIANCE_UNION,
    EVENT_TYPE_ALLIANCE_CREATED,
    EVENT_TYPE_ALLIANCE_DISSOLVED,
    EVENT_TYPE_ALLIANCE_MEMBER_JOINED,
    EVENT_TYPE_ALLIANCE_MEMBER_REMOVED,
    EVENT_TYPE_ALLIANCE_MILITARY_UPGRADED,
    EVENT_TYPE_ALLIANCE_MILITARY_DOWNGRADED,
    EVENT_TYPE_ALLIANCE_WAR_STARTED,
    EVENT_TYPE_ALLIANCE_WAR_ENDED,
    EVENT_TYPE_WORLD_TECH_AGE_FIRST,
    EVENT_TYPE_WORLD_DEEP_SEA_FIRST
} EventLogType;

typedef enum {
    EVENT_SEVERITY_INFO,
    EVENT_SEVERITY_WARNING,
    EVENT_SEVERITY_DANGER
} EventLogSeverity;

#endif
