#ifndef WORLD_SIM_WIND_SAMPLE_CONTRACT_H
#define WORLD_SIM_WIND_SAMPLE_CONTRACT_H

enum {
    WORLD_WIND_SAMPLE_COARSE_COLUMNS = 12,
    WORLD_WIND_SAMPLE_COARSE_ROWS = 8,
    WORLD_WIND_SAMPLE_MEDIUM_COLUMNS = 24,
    WORLD_WIND_SAMPLE_MEDIUM_ROWS = 16,
    WORLD_WIND_SAMPLE_FINE_COLUMNS = 32,
    WORLD_WIND_SAMPLE_FINE_ROWS = 24,
    WORLD_WIND_SAMPLE_COARSE_COUNT =
        WORLD_WIND_SAMPLE_COARSE_COLUMNS * WORLD_WIND_SAMPLE_COARSE_ROWS,
    WORLD_WIND_SAMPLE_MEDIUM_COUNT =
        WORLD_WIND_SAMPLE_MEDIUM_COLUMNS * WORLD_WIND_SAMPLE_MEDIUM_ROWS,
    WORLD_WIND_SAMPLE_FINE_COUNT =
        WORLD_WIND_SAMPLE_FINE_COLUMNS * WORLD_WIND_SAMPLE_FINE_ROWS
};

#endif
